blog/urls.py
from django.urls import path, include
from .views import render_posts,post_detail

app_name = "blog"

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail'),

]

django_web_model/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
from blog import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', views.profile, name="profile"),
    path('logout/', views.logout, name="logout"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
class Post(models.Model):
    tittle = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from distutils.command.upload import upload
from unittest.util import _MAX_LENGTH
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    tittle = CharField(max_length = 100)
    description = CharField(max_length = 250)
    image = ImageField(upload_to="portfolio/images/")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post


def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'post.html', {'posts' : posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post": post})

portfolio/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from .models import Project
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})


@login_required
def salir(request):
    logout(request)
    return redirect('/')

def profile(request):

    projects = Project.objects.all()
    return render(request, 'profile.html', {'projects': projects})

blog/templates/post.html
{% include 'partials/navbar.html' %}
{% block content %}

{% for post in posts %}
<body class="bg-black">
<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.tittle}}" class="img-fluid">
            </div>
            <div class="col-9 text-light">
                <h3>{{post.tittle}}</h3>
                <p>{{post.description|striptags|truncatechars:100}}</p> 
                <p>{{ post.date|date:'M d Y' }}</p>
            
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-light">{{post.tittle}}</a>
            </div>
        </div>
    </div>
</div>
</body>
{% endfor %}
{% endblock %}

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}
<body class="bg-black">
    <div class="text-center text-light">
    <h2>{{post.tittle}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>
    <img src="{{post.image.url}}" alt="{{post.tittle}}" class="img-fluid" height="500" width="500">
    <div class="my-4">
    <p>{{post.description|safe}}</p> 
    </div>
</div>
</body>
{% endblock %}

portfolio/templates/home.html
{% load static %} {% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="shortcut icon" href="{% static 'portfolio/icono.ico' %} ">
    <title>Home</title>
</head>
<body class="text-light bg-b"> 
    {% include 'partials/navbar.html' %} 
    <div class="container p-4">
    <header class="row bg-black">
        <div class="col-md-5 my-auto">
            <img src="{% static 'portfolio/profile.jpg' %}" width="400" height="400" alt="">
        </div>
        <div class="col-md-6">
            <h1>I am <strong>Gustavo Quintero</strong></h1>
            <h3>I am Software Developer,</h3>
            <p>I love computers, technology, and search solutions for new problems.</p>
            <h2>What are your favorite hobbies?</h2>
            <p>My favorite hobby is repair computers and learn some algorithms in different Programming languages.</p>
            <h2>What's your dream job?</h2>
            <p>My dream job is work with Artificial Inteligence, because AI systems utilize a whole series of techniques and processes.</p>
            <h2>Experience?</h2>
            <p>Currently, I have experience in web programming, from the layout in HTML to the connection with the database. Also, i'm 
              learning python and another languages, such as scripting and computer security.
              </p>
            <h2>Why do you want to be a web developer?</h2>
            <p>Because, i think IT has many fields to investigate,
              and nowadays the world is entering to a new era, where different companies will
              need do their own software to be known.</p>
            <a class="btn btn-outline-light" href="{% static 'portfolio/CV.pdf' %}" target="_blank">Download CV</a>
        </div>
    </header>
    <div class="row my-4 text-center ">
        <h3>My projects</h3>
        <p>This section redirects  to my own projects uploaded on GitHub.</p>
        {% for project in projects %}
        <div class="col-md-4 p-4">
            <div class="card bg-black card-project h-100">
                <img src="{{project.image.url}}" alt="{{project.tittle}}" class="card-img-top rounded-2 p-4" width="300" 
                height="250">
                <div class="card-body">
                    <h2>
                        {{project.tittle}}
                    </h2>
                    <p>
                        {{project.description}}
                    </p>
                    {% if project.url %}
                        <a href="{{project.url}}" class="align-self-end btn btn-outline-light rounded-2" target="_blank">Go to Github</a>
                    {% endif %} 
                </div>
            </div>
        </div>
        {% endfor %} 
    {% endblock %}        
    </div>
    <h3 class=" text-center">And more projects in process...</h3>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Django portFolio</title>
</head>
<body>
    {% include 'partials/navbar.html' %}
    <div class="container p-4">
    {% block content %}
    {% endblock %}
    </div>
    <footer>Footer</footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
      <nav class="navbar navbar-expand-lg p-3" style="background-color: black;">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <img src="{% static 'portfolio/icono.ico' %} " width="70" height="70" alt="">
          </a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link text-light" aria-current="page" href="/">HOME</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="/blog/">PORTFOLIO</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="/accounts/login/">LOGIN</a>
              </li>
            </ul>
            <li class="nav-item d-flex align-item-center"></li>
              <a class="btn btn-outline-light" href="{% static 'portfolio/CV.pdf' %}" target="_blank">Download CV</a>
          </div>
        </div>
      </nav>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>